### ISSUE TITLE
Indexing fails

### ISSUE THREAD

**Issue by shanavas786** [ojuba-org/thawab#13]
indexing books fails with error

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/shanavas/dev/debian/thawab/thawab-github/Thawab/asyncIndex.py", line 104, in _worker
    f(*args,**kw)
  File "/home/shanavas/dev/debian/thawab/thawab-github/Thawab/baseSearchEngine.py", line 241, in indexKitab
    iix)
  File "/home/shanavas/dev/debian/thawab/thawab-github/Thawab/core.py", line 884, in traverser
    nodeEnd(stack[-1], *args)
  File "/home/shanavas/dev/debian/thawab/thawab-github/Thawab/baseSearchEngine.py", line 208, in __ix_nodeEnd
    self.addDocumentToIndex(unicode(name), vrr, n, t.strip(), c, T)
  File "/home/shanavas/dev/debian/thawab/thawab-github/Thawab/whooshSearchEngine.py", line 266, in addDocumentToIndex
    tags = tags)
  File "/usr/lib/python2.7/dist-packages/whoosh/writing.py", line 750, in add_document
    for tbytes, freq, weight, vbytes in items:
  File "/usr/lib/python2.7/dist-packages/whoosh/fields.py", line 164, in index
    for tstring, freq, wt, vbytes in word_values(value, ana, **kwargs):
  File "/usr/lib/python2.7/dist-packages/whoosh/formats.py", line 146, in word_values
    wordset = set(t.text for t in tokens(value, analyzer, kwargs))
  File "/usr/lib/python2.7/dist-packages/whoosh/formats.py", line 125, in tokens
    gen = analyzer(value, **kwargs)
TypeError: 'NoneType' object is not callable
```

**Comment by linuxer9** [comment]
please mention the distribution, and books you're trying to index

**Comment by shanavas786** [comment]
Debian stretch,
I have tried several books from shamela.ws. All of them fails with the same error.

**Comment by linuxer9** [comment]
working on it , thanks for reporting.

**Comment by linuxer9** [comment]
please test this 
https://github.com/ojuba-org/thawab/commit/bdf723cd7de78d1e3967c470b563d03e18d75c95

**Comment by shanavas786** [comment]
That fixes it 👍

**Comment by shanavas786** [comment]
Is there any plan for new version release after this fix so that debian package can be updated ?

**Comment by linuxer9** [comment]
just finishing webkit2 port and we release that new version

**Comment by shanavas786** [comment]
@linuxer9 👍
