### ISSUE TITLE
Migrate to Python3

### ISSUE THREAD

**Issue by aelmahmoudy** [ojuba-org/thawab#17]
Python2 has reached end-of-life, please migrate thawab to Python3.

**Comment by aelmahmoudy** [comment]
I have done the migration in python3 branch, yet I get this error:

Traceback (most recent call last):
  File "/usr/bin/thawab-gtk", line 5, in <module>
    from Thawab.gtkUi import main
  File "/usr/share/thawab/Thawab/gtkUi.py", line 35, in <module>
    from Thawab.shamelaUtils import ShamelaSqlite, shamelaImport
  File "/usr/share/thawab/Thawab/shamelaUtils.py", line 51, in <module>
    os.urandom(hashlen*3/4).encode('base64')[:hashlen]
TypeError: integer argument expected, got float

can you help ?

**Comment by saad440** [comment]
I haven't looked at the whole code yet but it looks like it is because of the division (hashlen*3/4) which comes out as a float, not an integer. May be convert it to an int first?

**Comment by aelmahmoudy** [comment]
I changed the line to:
    os.urandom(int(hashlen*3/4)).encode('base64')[:hashlen]

Now I get this error:
AttributeError: 'bytes' object has no attribute 'encode'

**Comment by saad440** [comment]
urandom() is probably returning bytes rather than a string. Try decode instead of encode.

**Comment by muayyad-alsadi** [comment]
```python
from base64 import b64encode
b64encode(os.urandom(int(hashlen*3/4)))[:hashlen]
```

**Comment by aelmahmoudy** [comment]
After applying your fix, another error appeared:

```
Exception happened during processing of request from ('127.0.0.1', 60638)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/okasha/baseWebApp.py", line 605, in __call__
    try: r=f(rq, *a)
  File "/usr/share/thawab/Thawab/webApp.py", line 88, in _root
    raise redirectException(rq.script+'/index/')
okasha.baseWebApp.webAppBaseException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 304, in wsgi_execute
    self.wsgi_start_response)
  File "/usr/lib/python3/dist-packages/okasha/baseWebApp.py", line 608, in __call__
    return self._handleException(rq, e)
  File "/usr/lib/python3/dist-packages/okasha/baseWebApp.py", line 503, in _handleException
    return getattr(self, s)(rq, e)
  File "/usr/lib/python3/dist-packages/okasha/baseWebApp.py", line 521, in _302
    return ("Redirect to "+ e.kw['location'],)
TypeError: must be str, not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 324, in wsgi_execute
    self.wsgi_write_chunk("Internal Server Error\n")
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
```

**Comment by aelmahmoudy** [comment]
I modified baseWebApp.py in okasha as follows:

```python
   return ("Redirect to "+ str(e.kw['location']),) 
```

So the first 2 exceptions are gone, yet the last exception occurs twice but 
with different port numbers:

```
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33916)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 307, in wsgi_execute
    self.wsgi_write_chunk(chunk)
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 33918)
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 1085, in process_request_in_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 459, in handle
    BaseHTTPRequestHandler.handle(self)
  File "/usr/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 454, in handle_one_request
    self.wsgi_execute()
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 307, in wsgi_execute
    self.wsgi_write_chunk(chunk)
  File "/usr/lib/python3/dist-packages/paste/httpserver.py", line 167, in wsgi_write_chunk
    self.wfile.write(chunk)
  File "/usr/lib/python3.6/socketserver.py", line 803, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'str'
----------------------------------------

```

although netstat reports that thawab-gtk is listening to port 18080.

**Comment by aelmahmoudy** [comment]
I modified baseWebApp.py (again) in okasha as follows:

```python
   return (("Redirect to "+ str(e.kw['location'])).encode('utf-8'),) 
```

So the exception occurs only once.

**Comment by aelmahmoudy** [comment]
@muayyad-alsadi I am stuck here. Please help

**Comment by aelmahmoudy** [comment]
Please try to fix this as soon as possible.

**Comment by michele-musa** [comment]
Thawab doesn't open in Ubuntu 20.04. 
Importing 'escape' from cgi fails under python3.8
at line 25 of Thawab/webApp.py

**Comment by aelmahmoudy** [comment]
@ehabsas I see you've been working on this issue, is it fixed yet ?
